### ISSUE TITLE
Can't make it a plugin

### ISSUE THREAD

**Issue by File14** [rutgerkok/Pokkit#1] opened 2016-07-27 16:56 UTC
Errors on mvn install: http://hastebin.com/ojoqexuqav.py

**Comment by rutgerkok** [comment] 2016-07-30 08:37
It complains about the class ExperienceOrbSounc being lost. I would try to compile an updated version of Nukkit first, and see if that helps.

If you just want a compiled JAR file, you can download one [here](https://dl.dropboxusercontent.com/u/23288978/Pokkit.jar).

**Comment by rutgerkok** [comment] 2016-08-23 08:43
Closing this, as I cannot reproduce this.

**Closed by rutgerkok** 2016-08-23 08:43 UTC
