### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by OverTook** [rutgerkok/Pokkit#18] opened 2016-10-02 10:12 UTC
[ERROR] [Pokkit] Error loading plugin
java.lang.NoClassDefFoundError: org/bukkit/Server
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
        at java.lang.Class.getConstructor0(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at nl.rutgerkok.pokkit.startup.NukkitHook.onLoad(NukkitHook.java:39)
        at cn.nukkit.plugin.JavaPluginLoader.initPlugin(JavaPluginLoader.java:112)
        at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:54)
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:96)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:278)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:133)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:125)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:121)
        at cn.nukkit.Server.<init>(Server.java:379)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.ClassNotFoundException: org.bukkit.Server
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at nl.rutgerkok.pokkit.startup.UrlFirstClassLoader.loadClass(UrlFirstClassLoader.java:50)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 14 more

when i turn on the server, this happended

**Comment by rutgerkok** [comment] 2016-10-02 13:32
Cannot reproduce. I am using this file:

https://dl.dropboxusercontent.com/u/23288978/Pokkit.jar

**Comment by rutgerkok** [comment] 2016-10-08 16:00
I'm closing this issue. @OverTook, feel free to respond here if you have any questions. By now, you can probably better [download the latest release from here](https://github.com/rutgerkok/Pokkit/releases).

**Closed by rutgerkok** 2016-10-08 16:00 UTC
Labels: Complete
